---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=2cm
papersize: a4
title: "Resume"
author: Maximilian Held

jobtitle: "Social Data Scientist"
address: "Herrnstraße 41 · 90763 Fürth · Germany"
fontawesome: true
email: info@maxheld.de
github: maxheld83
twitter: maxheld
phone: "+49 151 22958775"
web: maxheld.de
updated: false

keywords: R Markdown, academic CV, template

fontsize: 11pt
linkcolor: yes
---

Born 1983 in Bremen, Germany.


# Experience

[*RStudio Inc.*](https://www.rstudio.com/): Software Engineer (Contract) \hfill 05-08/2019
\newline
(Developing the [ghactions](https://r-lib.github.io/ghactions/) R package.)

[*Friedrich-Alexander Universität Erlangen-Nürnberg*](https://www.fau.de): Research Associate \hfill since 2018
\newline
(Data Science).

[*Universität Hohenheim*](https://www.uni-hohenheim.de): Research Associate (Data Science). \hfill 2016 -- 2018

[*Jacobs University Bremen*](https://www.jacobs-university.de): Research Associate \hfill 2015 -- 2016
\newline (Computational Social Science).

[*Jacobs University Bremen*](https://www.jacobs-university.de): Lecturer ("[German Politics and Culture](http://www.maxheld.de/gpc/)"). \hfill 2010 -- 2015

[*Dacapo Unternehmensberatung GmbH*](http://dacapo2.com/), Berlin: Visiting Consultant (Financial Modelling) \hfill 2006

<!-- [*Universität Hamburg*](https://www.uni-hamburg.de): Lehrauftrag ("[Progressive Taxation and Deliberative Democracy](https://www.maxheld.de/give-n-take/)") \hfill 2014 -->


# Education

[*Universität Bremen*](https://www.bigsss-bremen.de): [Dissertation](https://www.maxheld.de/schumpermas) on taxation and democracy.\hfill since 2010 
\newline Completion expected in 2019.

[*Hertie School of Governance*](https://www.hertie-school.org): Graduate Studies Public Policy. \hfill 2008 -- 2010

[*Berlin Studies Centre*](http://studienkolleg-zu-berlin.de): Fellowship. \hfill 2008 -- 2009

[*Fulbright Commission*](https://eca.state.gov/fulbright), Washington, DC (USA): Fellowship. \hfill 2007 -- 2008

[*University of California, Irvine*](https://www.uci.edu) (Irvine, CA USA): Graduate Studies Social Sciences. \hfill 2007 -- 2008

[*Jacobs University Bremen*](https://www.jacobs-university.de): BA Integrated Social Sciences (Presidents List). \hfill 2004 -- 2007

[*German National Academic Foundation*](https://www.studienstiftung.de/): Fellowship. \hfill 2004 -- 2010

[*Gymnasium Syke*](http://gymnasium-syke.de): Bilingual High School (Graduated best in class). \hfill 1996 -- 2003


# Volunteering and Service

[*International Society for the Scientific Study of Human Subjectivity* ](https://qmethod.org), Columbia, MS (USA):\newline
Webmaster. \hfill since 2015

[*Deutsche SchülerAkadamie / Bildung & Begabung gGmbH*, Bonn](https://www.deutsche-schuelerakademie.de):\newline
Teacher and Manager. \hfill since 2003


# Skills

[R](http://r-project.org) (expert knowledge, package development), data visualisation and [Shiny](http://shiny.rstudio.com) (advanced), HTML5/CSS/JS, exploratory data analysis, unsupervised learning.

Also: [Git](https://git-scm.com), [GitHub](https://github.com), [Docker](https://www.docker.com), CI/CD, [Tidyverse](https://www.tidyverse.org), [LaTeX](http://latex-project.org), Bash, Linux, macOS.

Fluent in english and german.

Last updated \today.
