---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
lang: de
geometry: margin=2cm
papersize: a4
title: "Lebenslauf"
author: Maximilian Held

jobtitle: "Social Data Scientist"
address: "Herrnstraße 41 · 90763 Fürth"
fontawesome: true
email: info@maxheld.de
github: maxheld83
twitter: maxheld
phone: "+49 151 22958775"
web: maxheld.de
updated: false

keywords: R Markdown, academic CV, template

fontsize: 11pt
linkcolor: yes
---

Geboren 1983 in Bremen.


# Arbeitserfahrung

[*RStudio Inc.*](https://www.rstudio.com/): Softwareentwickler (Freiberuflich) \hfill 05-08/2019
\newline
(Entwicklung des [ghactions](https://r-lib.github.io/ghactions/) R Pakets.)

[*Friedrich-Alexander Universität Erlangen-Nürnberg*](https://www.fau.de): Wissenschaftlicher Mitarbeiter \hfill seit 2018
\newline
(Data Science)

[*Universität Hohenheim*](https://www.uni-hohenheim.de): Wissenschaftlicher Mitarbeiter (Data Science) \hfill 2016 -- 2018

[*Jacobs University Bremen*](https://www.jacobs-university.de): Wissenschaftlicher Mitarbeiter \hfill 2015 -- 2016
\newline (Computational Social Science)

<!-- [*Universität Hamburg*](https://www.uni-hamburg.de): Lehrauftrag ("[Progressive Taxation and Deliberative Democracy](https://www.maxheld.de/give-n-take/)") \hfill 2014 -->

[*Jacobs University Bremen*](https://www.jacobs-university.de): Lehrauftrag ("[German Politics and Culture](http://www.maxheld.de/gpc/)") \hfill 2010 -- 2015

[*Dacapo Unternehmensberatung GmbH*](http://dacapo2.com/), Berlin: Praktikum (Due Diligence, Modellierung) \hfill 2006


# Ausbildung

[*Universität Bremen*](https://www.bigsss-bremen.de): [Dissertation](https://www.maxheld.de/schumpermas) über Steuern und Demokratie.\hfill seit 2010 
\newline Abschluss erwartet 2019. 

[*Hertie School of Governance*](https://www.hertie-school.org):  Studium Public Policy \hfill 2008 -- 2010

[*Studienkolleg zu Berlin*](http://studienkolleg-zu-berlin.de): Kollegiat \hfill 2008 -- 2009

[*Fulbright Commission*](https://eca.state.gov/fulbright), Washington, DC (USA): Stipendium \hfill 2007 -- 2008

[*University of California, Irvine*](https://www.uci.edu) (Irvine, CA USA): Studium Sozialwissenschaften \hfill 2007 -- 2008

[*Jacobs University Bremen*](https://www.jacobs-university.de): BA Sozialwissenschaft mit Auszeichnung \hfill 2004 -- 2007

[*Studienstiftung des Deutschen Volkes*](https://www.studienstiftung.de/): Stipendium \hfill 2004 -- 2010

[*Gymnasium Syke*](http://gymnasium-syke.de): bilingualer Zweig, Abiturnote 1.5 \hfill 1996 -- 2003


# Ehrenamt

[*International Society for the Scientific Study of Human Subjectivity* ](https://qmethod.org), Columbia, MS (USA):\newline
Vorstandsmitglied und Webmaster \hfill seit 2015

[*Deutsche SchülerAkadamie / Bildung & Begabung gGmbH*, Bonn](https://www.deutsche-schuelerakademie.de):\newline
Kurs- und Akademieleitung \hfill seit 2003


# Fähigkeiten

[R](http://r-project.org) (Experte, Package-Entwicklung), Datenvisualisierung und [Shiny](http://shiny.rstudio.com) (fortgeschritten), HTML5/CSS/JS und Unsupervised Learning, Explorative Datenanalyse.

Außerdem: [Git](https://git-scm.com), [GitHub](https://github.com), [Docker](https://www.docker.com), CI/CD, [Tidyverse](https://www.tidyverse.org), [LaTeX](http://latex-project.org), Wordpress, Bash, Linux, macOS.

Englisch verhandlungssicher in Wort und Schrift.

\vspace*{5mm}

Nürnberg, den \today.
